#!dev/python.sh
import os
import re
import sys
from collections import OrderedDict
from pathlib import Path

sys.path.append(os.getcwd())
from dev.metadata import PACKAGE_GENERIC_INFO, PACKAGE_SPECIFIC_INFO
from dev.version import __version__

versions_info = dict(walt_version=__version__)


def generate_pyproject(package_name):
    package_specific = PACKAGE_SPECIFIC_INFO[package_name]
    subdir = Path(package_specific["subdir"])
    # remove obsolete info.py file if it exists
    subdir_as_path = str(subdir).replace("-", "/")  # client-g5k -> client/g5k
    obsolete_info_py = subdir / "walt" / subdir_as_path / "info.py"
    if obsolete_info_py.exists():
        obsolete_info_py.unlink()
    # prepare package setup info
    setup_info = OrderedDict()
    setup_info.update(name=package_name)
    version = package_specific["version_str"] % versions_info
    setup_info.update(version=version)
    requirements_txt = subdir / "requirements.txt"
    if requirements_txt.exists():
        uncommented = re.sub(r"#[^\n]*\n", "", requirements_txt.read_text())
        install_requires = uncommented.strip().splitlines()
    else:
        install_requires = [
            requirement % versions_info for requirement in package_specific["requires"]
        ]
    setup_info.update(install_requires=install_requires)
    if "extras_require" in package_specific:
        extras_require = {
            feature: [(req % versions_info) for req in requirements]
            for (feature, requirements) in package_specific["extras_require"].items()
        }
        setup_info.update(extras_require=extras_require)
    setup_info.update(sorted(PACKAGE_GENERIC_INFO.items()))
    setup_info.update(sorted(package_specific["setup"].items()))
    setup_info = dict(**setup_info)  # convert back to dict
    # write pyproject.toml file
    pyproject = subdir / "pyproject.toml"
    pyproject.touch()
    pyproject.write_text(f"""\
# auto-generated by dev/setup-updater.py
# using metadata from dev/metadata.py
[build-system]
build-backend = "setuptools.build_meta"

requires = {(["setuptools>=77", "wheel>=0.31"] + (setup_info["setup_requires"] if "setup_requires" in setup_info else []))}

[project]
name = "{package_name}"
description = "{setup_info["description"]}"
readme = {{ file = "README.txt", content-type = "text/text" }}
keywords = [ "{PACKAGE_GENERIC_INFO["keywords"]}" ]
license = "{ PACKAGE_GENERIC_INFO["license"] }"
authors = [ {{ name = "{PACKAGE_GENERIC_INFO["author"]}", email = "{PACKAGE_GENERIC_INFO["author_email"]}" }} ]

requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Systems Administration",
  "Topic :: Utilities"
]

version = "{setup_info["version"]}"
dependencies ={ setup_info["install_requires"] }

[dependency-groups]
dev = [
  "build",
  "ruff",
  "black",
]

{f"[project.scripts]\n{"\n".join([x.replace(x.split("=")[1], f"'{x.split("=")[1].replace(" ", "")}'") for x in setup_info['entry_points']['console_scripts']])}" if "entry_points" in setup_info and "console_scripts" in setup_info["entry_points"] else ""}
[project.urls]
homepage = "{PACKAGE_GENERIC_INFO["url"]}"
documentation = "{PACKAGE_GENERIC_INFO["url"]}"
repository = "{PACKAGE_GENERIC_INFO["url"]}"

[tool.setuptools]
include-package-data = true
{("packages = [\"sh\"]\nscript-files = "+ repr(setup_info['scripts'])) if "scripts" in setup_info else ""}

""")


if __name__ == "__main__":
    if len(sys.argv) == 2:
        # reformat one setup.py
        package_name = sys.argv[1]
        generate_pyproject(package_name)
    else:
        # reformat all setup.py files
        for package_name in PACKAGE_SPECIFIC_INFO.keys():
            generate_pyproject(package_name)
