# auto-generated by dev/setup-updater.py
# using metadata from dev/metadata.py

import sys

from setuptools import find_packages, setup

if sys.version_info[0] == 2:
    sys.exit("Sorry, Python 2 is no longer supported.")

setup_info = {
    "name": "walt-server",
    "version": "10.0",
    "install_requires": [
        "plumbum>=1.7.2",
        "snimpy>=1.0.3",
        "ipaddress>=1.0.7",
        "requests>=2.21.0",
        "sdnotify>=0.3.0",
        "psycopg2-binary>=2.8.2",
        "gevent>=21.1.2",
        "bottle>=0.12.19",
        "aiohttp>=3.10.11",
        "aiostream>=0.4.4",
        "netifaces>=0.11.0",
        "podman>=4.2.0",
        "setproctitle>=1.3.2",
        "numpy>=1.24.3",
        "numba>=0.58.1",
        "cffi>=1.16.0",
        "dnspython>=2.7.0",
        "walt-client==10.0",
        "walt-common==10.0",
        "walt-doc==10.0",
        "walt-virtual==10.0",
    ],
    "author": "WalT developers",
    "author_email": "walt-contact@univ-grenoble-alpes.fr",
    "keywords": "WalT testbed",
    "license": "3-Clause BSD",
    "url": "https://walt-project.liglab.fr",
    "cffi_modules": ["walt/server/ext/build.py:ffibuilder"],
    "description": "WalT server components.",
    "entry_points": {
        "console_scripts": [
            "walt-server-setup = walt.server.setup.main:run",
            "walt-server-daemon = walt.server.daemon:run",
            "walt-server-httpd = walt.server.services.httpd:run",
            "walt-server-tftpd = walt.server.services.tftpd:run",
            "walt-server-snmpd = walt.server.services.snmpd:run",
            "walt-server-lldpd = walt.server.services.lldpd:run",
            "walt-server-ptpd = walt.server.services.ptpd:run",
            "walt-server-nbd = walt.server.services.nbd:run",
            "walt-server-trackexec-replay = walt.server.trackexec.player:run",
            "walt-server-trackexec-analyse = walt.server.trackexec.analyse:run",
            "walt-dhcp-event = walt.server.dhcpevent:run",
            "walt-net-config = walt.server.netconfig:run",
            "walt-image-check = walt.server.imagecheck:run",
            "walt-annotate-cmd = walt.server.annotatecmd:run",
            "walt-image-mount = walt.server.mount.mount:run",
            "walt-image-umount = walt.server.mount.umount:run",
            "walt-set-poe = walt.server.snmp.run:walt_set_poe",
            "walt-server-vpn = walt.server.services.vpn:run",
            "walt-server-vpn-endpoint = walt.server.vpn.endpoint:run",
            "walt-vpn-admin = walt.server.vpn.admin:run",
        ]
    },
    "include_package_data": True,
    "scripts": [
        "sh/walt-image-shell-helper",
        "sh/walt-image-build-helper",
        "sh/walt-image-fs-helper",
        "sh/walt-server-cleanup",
        "sh/walt-device-ssh",
        "sh/walt-server-vpn-test-ssh-entrypoint",
    ],
    "setup_requires": ["cffi>=1.16.0"],
}
setup_info.update(packages=find_packages())
setup(**setup_info)
